# ============================
# PROD PROFILE ? Railway deploy
# ============================

# Datasource
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.database=POSTGRESQL
spring.sql.init.platform=postgres

# DDL: update para despliegues sin Flyway/Liquibase
spring.jpa.hibernate.ddl-auto=validate

# Logging minimo en prod
spring.jpa.show-sql=false
logging.level.com.crishof=INFO
logging.level.root=WARN

# Actuator
management.endpoint.health.show-details=never

# Swagger deshabilitado en prod
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
